<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>RiderIlSpy.Contracts</AssemblyName>
    <RootNamespace>RiderIlSpy</RootNamespace>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="RiderIlSpy" />
    <InternalsVisibleTo Include="RiderIlSpy.Engine" />
    <InternalsVisibleTo Include="RiderIlSpy.Tests" />
  </ItemGroup>

</Project>
